def test_services_importable():
    from app.services import (
        AgentRunService,
        ApplicationPacketService,
        ApplicationPrepService,
        CompanyPageService,
        CompanyService,
        CrawlRunService,
        DiscoveryService,
        HimalayasRemoteJobDiscoveryService,
        JobApplicationDecisionService,
        WeWorkRemotelyDiscoveryService,
        RemotiveRemoteJobDiscoveryService,
        RemoteJobDiscoveryOrchestratorService,
        ResumeService,
        ResumeImprovementService,
        JobMatchingService,
        JobMatchingProfileService,
        JobService,
        TechStackService,
        UserProfileService,
    )

    assert all(
        [
            AgentRunService,
            ApplicationPacketService,
            ApplicationPrepService,
            CompanyPageService,
            CompanyService,
            CrawlRunService,
            DiscoveryService,
            HimalayasRemoteJobDiscoveryService,
            JobApplicationDecisionService,
            WeWorkRemotelyDiscoveryService,
            RemotiveRemoteJobDiscoveryService,
            RemoteJobDiscoveryOrchestratorService,
            ResumeService,
            ResumeImprovementService,
            JobMatchingService,
            JobMatchingProfileService,
            JobService,
            TechStackService,
            UserProfileService,
        ]
    )
