"""add discovery deferral fields

Revision ID: 4955643c08b1
Revises: 8d2c7a4f1b9e
Create Date: 2026-07-08 23:14:27.445471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4955643c08b1'
down_revision: Union[str, None] = '8d2c7a4f1b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_candidates', sa.Column('deferred_reason', sa.String(), nullable=True))
    op.add_column(
        'discovery_runs',
        sa.Column(
            'candidates_deferred',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.alter_column(
        'discovery_runs',
        'candidates_deferred',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_runs', 'candidates_deferred')
    op.drop_column('discovery_candidates', 'deferred_reason')
    # ### end Alembic commands ###
