"""initial domain models

Revision ID: cc58dd933593
Revises: 
Create Date: 2026-07-04 23:44:37.584488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc58dd933593'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('normalized_domain', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('unknown', 'pre_seed', 'seed', 'series_a', 'series_b', 'growth', 'public', name='companystage', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('manual', 'yc', 'product_hunt', 'hacker_news', 'wellfound', 'company_website', 'rss', 'other', name='companysource', native_enum=False), nullable=False),
    sa.Column('employee_count_min', sa.Integer(), nullable=True),
    sa.Column('employee_count_max', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_normalized_domain'), 'companies', ['normalized_domain'], unique=True)
    op.create_table('user_profiles',
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.Enum('unknown', 'onsite', 'hybrid', 'remote_country', 'remote_region', 'remote_worldwide', name='remotetype', native_enum=False), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('strong_skills', sa.JSON(), nullable=True),
    sa.Column('weak_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_company_stages', sa.JSON(), nullable=True),
    sa.Column('preferred_company_sizes', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_pages',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('page_type', sa.Enum('homepage', 'about', 'careers', 'jobs', 'team', 'blog', 'engineering', 'docs', 'pricing', 'unknown', name='pagetype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('html_hash', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'url')
    )
    op.create_index(op.f('ix_company_pages_company_id'), 'company_pages', ['company_id'], unique=False)
    op.create_index('ix_company_pages_page_type', 'company_pages', ['page_type'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='crawlstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pages_found', sa.Integer(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_company_id'), 'crawl_runs', ['company_id'], unique=False)
    op.create_index('ix_crawl_runs_status', 'crawl_runs', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('normalized_title', sa.String(), nullable=True),
    sa.Column('role_category', sa.Enum('ai_engineer', 'backend_engineer', 'software_engineer', 'ml_engineer', 'data_engineer', 'full_stack_engineer', 'frontend_engineer', 'devops_engineer', 'product_engineer', 'other', name='rolecategory', native_enum=False), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote_type', sa.Enum('UNKNOWN', 'ONSITE', 'HYBRID', 'REMOTE_COUNTRY', 'REMOTE_REGION', 'REMOTE_WORLDWIDE', name='remotetype', native_enum=False), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('source_platform', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'UNKNOWN', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_url')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_title'), 'jobs', ['normalized_title'], unique=False)
    op.create_index('ix_jobs_remote_type', 'jobs', ['remote_type'], unique=False)
    op.create_index('ix_jobs_role_category', 'jobs', ['role_category'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('tech_stack_items',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', 'source')
    )
    op.create_index('ix_tech_stack_items_company_id', 'tech_stack_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_tech_stack_items_name'), 'tech_stack_items', ['name'], unique=False)
    op.create_table('agent_runs',
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_company_id'), 'agent_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_job_id'), 'agent_runs', ['job_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_table('agent_steps',
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_name'), 'agent_steps', ['step_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_steps_step_name'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_job_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_company_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_tech_stack_items_name'), table_name='tech_stack_items')
    op.drop_index('ix_tech_stack_items_company_id', table_name='tech_stack_items')
    op.drop_table('tech_stack_items')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index('ix_jobs_role_category', table_name='jobs')
    op.drop_index('ix_jobs_remote_type', table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_crawl_runs_status', table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_company_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index('ix_company_pages_page_type', table_name='company_pages')
    op.drop_index(op.f('ix_company_pages_company_id'), table_name='company_pages')
    op.drop_table('company_pages')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_companies_normalized_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
